# Generated by Django 5.0.7 on 2024-07-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_no_of_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
