# Generated by Django 5.0.7 on 2024-07-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_image_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
